---
- name: Create a PostgreSQL DB server
  hosts: dbserver
  sudo: yes
  sudo_user: root
  remote_user: ubuntu
  tasks:
- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql
    - postgresql-contrib
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name=atc
             encoding='UTF-8'
             lc_collate='en_US.UTF-8'
             lc_ctype='en_US.UTF-8'
             template='template0'
             state=present

- name: restart postgresql
  service: name=postgresql state=restarted
  

