---
- name: Create a PostgreSQL DB server
  hosts: dbserver
  become: true 

  tasks:

  - name: Ensure bash, OpenSSl, and libssl are the latest versions
    apt: name={{ item }} update_cache=true state=latest
    with_items:
      - bash
      - openssl
      - libssl-dev
      - libssl-doc
    tags: packages

  - name: Install PostgreSQL
    apt: name={{ item }} update_cache=true state=present
    with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
    tags: packages

  - name: install prerequisites
    #sudo: true
    apt: name={{ item }} state=latest
    with_items:
      - libpq-dev
      - python-psycopg2
    tags:
      - packages
  - name: Connect to acme database, create django user, and grant access to database and products table
    postgresql_user:
     db: atc
     name: postgres
     password: postgres
     
  - name: Ensure the PostgreSQL service is running
    service: name=postgresql state=started enabled=yes

  - name: ensure database is created
    postgresql_db: name=atc

  - name: Ensure database is created
    #sudo_user: postgres
    postgresql_db: name=atc
              encoding='UTF-8'
              lc_collate='en_US.UTF-8'
              lc_ctype='en_US.UTF-8'
              template='template0'
              state=present

  - name: restart postgresql
    service: name=postgresql state=restarted


