---
- name: Installing Postgresql and Concourse
  hosts: postgre
  become: true 

  tasks:

    - name: Ensure bash, OpenSSl, and libssl are the latest versions
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
      tags: packages

    - name: Install PostgreSQL
      apt: name={{ item }} update_cache=true state=present
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python-psycopg2
        - python3-psycopg2
      tags: packages

    - name: install prerequisites
      #sudo: true
      apt: name={{ item }} state=latest
      with_items:
        - libpq-dev
        - python-psycopg2
        - python3-psycopg2
      tags:
        - packages

    - name: create a database
      postgresql_db:
          name: atc
          encoding: UTF-8
          template: template0
          state: present
      become_user: postgres
      become: yes
      
    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes

    - name: restart postgresql
      service: name=postgresql state=restarted
    