---
- hosts: dbserver
  become: yes

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: Install PostgreSQL
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2

- hosts: dbserver
  become: yes
  become_user: postgres

  vars:
    dbname: atc
    dbuser: concourse
    dbpassword: concourse



  tasks:



  - name: Connect to acme database, create django user, and grant access to database and products table
    postgresql_user:
     db: atc
     name: postgres
     password: postgres

  - name: Create a new database with name "acme"
    postgresql_db:
     name: atc

  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  
  - name: ensure no other user can access the database
    postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent